/**
 * WARNING: This is a generated file. Do not modify.
 *
 * Source: buildscripts/idl/idlc.py --include src --base_dir build/opt --target_arch x86_64 --header build/opt/mongo/transport/message_compressor_options_server_gen.h --output build/opt/mongo/transport/message_compressor_options_server_gen.cpp src/mongo/transport/message_compressor_options_server.idl
 */

#include "mongo/platform/basic.h"

#include "mongo/transport/message_compressor_options_server_gen.h"

#include <bitset>
#include <set>

#include "mongo/bson/bsonobjbuilder.h"
#include "mongo/db/command_generic_argument.h"
#include "mongo/db/commands.h"
#include "mongo/util/options_parser/option_section.h"
#include "mongo/util/options_parser/startup_option_init.h"
#include "mongo/util/options_parser/startup_options.h"

namespace mongo {


namespace  {
MONGO_MODULE_STARTUP_OPTIONS_REGISTER(idl_c5bbf443cc92544496ec264163a5abf7844bf6d5)(InitializerContext*) {
    auto& options = optionenvironment::startupOptions;
    namespace moe = ::mongo::optionenvironment;

    options
        .addOptionChaining("net.compression.compressors", "networkMessageCompressors", moe::String, "Comma-separated list of compressors to use for network messages", {}, {}, moe::OptionSection::OptionParserUsageType::IDLAutoGeneratedCode)
        .setSources(moe::SourceAll)
        .setDefault(moe::Value("snappy,zstd,zlib"))
    ;

    return Status::OK();
}
}  // namespace 

}  // namespace mongo
