/**
 * WARNING: This is a generated file. Do not modify.
 *
 * Source: buildscripts/idl/idlc.py --include src --base_dir build/opt --target_arch x86_64 --header build/opt/mongo/unittest/unittest_gen.h --output build/opt/mongo/unittest/unittest_gen.cpp src/mongo/unittest/unittest.idl
 */

#include "mongo/platform/basic.h"

#include "mongo/unittest/unittest_gen.h"

#include <bitset>
#include <set>

#include "mongo/bson/bsonobjbuilder.h"
#include "mongo/db/command_generic_argument.h"
#include "mongo/db/commands.h"
#include "mongo/util/options_parser/option_section.h"
#include "mongo/util/options_parser/startup_option_init.h"
#include "mongo/util/options_parser/startup_options.h"

namespace mongo {
namespace unittest {


namespace  {
MONGO_MODULE_STARTUP_OPTIONS_REGISTER(idl_b7370f83c98bca4c54a359323029f2be9c971198)(InitializerContext*) {
    auto& options = optionenvironment::startupOptions;
    namespace moe = ::mongo::optionenvironment;

    options
        .addOptionChaining("tempPath", "tempPath", moe::String, "Directory to place mongo::TempDir subdirectories", {}, {}, moe::OptionSection::OptionParserUsageType::IDLAutoGeneratedCode)
        .setSources(moe::SourceCommandLine)
    ;

    return Status::OK();
}
}  // namespace 

}  // namespace unittest
}  // namespace mongo
