/**
 * WARNING: This is a generated file. Do not modify.
 *
 * Source: buildscripts/idl/idlc.py --include src --base_dir build/opt --target_arch x86_64 --header build/opt/mongo/db/free_mon/free_mon_options_gen.h --output build/opt/mongo/db/free_mon/free_mon_options_gen.cpp src/mongo/db/free_mon/free_mon_options.idl
 */

#include "mongo/platform/basic.h"

#include "mongo/db/free_mon/free_mon_options_gen.h"

#include <bitset>
#include <set>

#include "mongo/bson/bsonobjbuilder.h"
#include "mongo/db/command_generic_argument.h"
#include "mongo/db/commands.h"
#include "mongo/util/options_parser/option_section.h"
#include "mongo/util/options_parser/startup_option_init.h"
#include "mongo/util/options_parser/startup_options.h"

namespace mongo {


namespace  {
MONGO_MODULE_STARTUP_OPTIONS_REGISTER(idl_2eb348f9af5be0f77ad3c59e0ae2febc206c1d79)(InitializerContext*) {
    auto& options = optionenvironment::startupOptions;
    namespace moe = ::mongo::optionenvironment;

    {
        moe::OptionSection section("Free Monitoring Options");

        section
            .addOptionChaining("cloud.monitoring.free.state", "enableFreeMonitoring", moe::String, "Enable Cloud Free Monitoring (on|runtime|off)", {}, {}, moe::OptionSection::OptionParserUsageType::IDLAutoGeneratedCode)
            .setSources(moe::SourceYAMLCLI)
        ;

        section
            .addOptionChaining("cloud.monitoring.free.tags", "freeMonitoringTag", moe::StringVector, "Cloud Free Monitoring Tags", {}, {}, moe::OptionSection::OptionParserUsageType::IDLAutoGeneratedCode)
            .setSources(moe::SourceYAMLCLI)
        ;

        auto status = options.addSection(section);
        if (!status.isOK()) {
            return status;
        }
    }

    return Status::OK();
}
}  // namespace 

}  // namespace mongo
