/**
 * WARNING: This is a generated file. Do not modify.
 *
 * Source: buildscripts/idl/idlc.py --include src --base_dir build/opt --target_arch x86_64 --header build/opt/mongo/db/mongod_options_legacy_gen.h --output build/opt/mongo/db/mongod_options_legacy_gen.cpp src/mongo/db/mongod_options_legacy.idl
 */

#include "mongo/platform/basic.h"

#include "mongo/db/mongod_options_legacy_gen.h"

#include <bitset>
#include <set>

#include "mongo/bson/bsonobjbuilder.h"
#include "mongo/db/command_generic_argument.h"
#include "mongo/db/commands.h"
#include "mongo/util/options_parser/option_section.h"
#include "mongo/util/options_parser/startup_option_init.h"
#include "mongo/util/options_parser/startup_options.h"

namespace mongo {


Status addMongodLegacyOptions(optionenvironment::OptionSection* options_ptr) {
    auto& options = *options_ptr;
    namespace moe = ::mongo::optionenvironment;

    options
        .addOptionChaining("command", "command", moe::StringVector, "Command", {}, {}, moe::OptionSection::OptionParserUsageType::IDLAutoGeneratedCode)
        .setSources(moe::SourceAllLegacy)
        .hidden()
        .positional(1, 3)
    ;

    options
        .addOptionChaining("cacheSize", "cacheSize", moe::Long, "Cache size (in MB) for rec store", {}, {}, moe::OptionSection::OptionParserUsageType::IDLAutoGeneratedCode)
        .setSources(moe::SourceAllLegacy)
        .hidden()
    ;

    options
        .addOptionChaining("pairwith", "pairwith", moe::Switch, "DEPRECATED", {}, {}, moe::OptionSection::OptionParserUsageType::IDLAutoGeneratedCode)
        .setSources(moe::SourceAllLegacy)
        .hidden()
    ;

    options
        .addOptionChaining("arbiter", "arbiter", moe::Switch, "DEPRECATED", {}, {}, moe::OptionSection::OptionParserUsageType::IDLAutoGeneratedCode)
        .setSources(moe::SourceAllLegacy)
        .hidden()
    ;

    options
        .addOptionChaining("opIdMem", "opIdMem", moe::Switch, "DEPRECATED", {}, {}, moe::OptionSection::OptionParserUsageType::IDLAutoGeneratedCode)
        .setSources(moe::SourceAllLegacy)
        .hidden()
    ;

    return Status::OK();
}

}  // namespace mongo
