/**
 * WARNING: This is a generated file. Do not modify.
 *
 * Source: buildscripts/idl/idlc.py --include src --base_dir build/opt --target_arch x86_64 --header build/opt/mongo/db/server_options_nongeneral_gen.h --output build/opt/mongo/db/server_options_nongeneral_gen.cpp src/mongo/db/server_options_nongeneral.idl
 */

#include "mongo/platform/basic.h"

#include "mongo/db/server_options_nongeneral_gen.h"

#include <bitset>
#include <set>

#include "mongo/bson/bsonobjbuilder.h"
#include "mongo/db/command_generic_argument.h"
#include "mongo/db/commands.h"
#include "mongo/util/options_parser/option_section.h"
#include "mongo/util/options_parser/startup_option_init.h"
#include "mongo/util/options_parser/startup_options.h"

namespace mongo {


Status addNonGeneralServerOptions(optionenvironment::OptionSection* options_ptr) {
    auto& options = *options_ptr;
    namespace moe = ::mongo::optionenvironment;

    {
        moe::OptionSection section("General options");

        section
            .addOptionChaining("net.bindIp", "bind_ip", moe::String, "Comma separated list of ip addresses to listen on - localhost by default", {}, {}, moe::OptionSection::OptionParserUsageType::IDLAutoGeneratedCode)
            .setSources(moe::SourceAll)
        ;

        section
            .addOptionChaining("net.bindIpAll", "bind_ip_all", moe::Switch, "Bind to all ip addresses", {}, {}, moe::OptionSection::OptionParserUsageType::IDLAutoGeneratedCode)
            .setSources(moe::SourceAll)
            .canonicalize(canonicalizeNetBindIpAll)
        ;

        section
            .addOptionChaining("noauth", "noauth", moe::Switch, "Run without security", {}, {}, moe::OptionSection::OptionParserUsageType::IDLAutoGeneratedCode)
            .setSources(moe::SourceAllLegacy)
            .incompatibleWith("auth")
            .incompatibleWith("security.keyFile")
            .incompatibleWith("security.transitionToAuth")
            .incompatibleWith("clusterAuthMode")
        ;

        section
            .addOptionChaining("security.transitionToAuth", "transitionToAuth", moe::Switch, "For rolling access control upgrade. Attempt to authenticate over outgoing connections and proceed regardless of success. Accept incoming connections with or without authentication.", {}, {}, moe::OptionSection::OptionParserUsageType::IDLAutoGeneratedCode)
            .setSources(moe::SourceAll)
            .incompatibleWith("noauth")
        ;

        section
            .addOptionChaining("operationProfiling.slowOpThresholdMs", "slowms", moe::Int, "Value of slow for profile and console log", {}, {}, moe::OptionSection::OptionParserUsageType::IDLAutoGeneratedCode)
            .setSources(moe::SourceAll)
            .setDefault(moe::Value(100))
        ;

        section
            .addOptionChaining("operationProfiling.slowOpSampleRate", "slowOpSampleRate", moe::Double, "Fraction of slow ops to include in the profile and console log", {}, {}, moe::OptionSection::OptionParserUsageType::IDLAutoGeneratedCode)
            .setSources(moe::SourceAll)
            .setDefault(moe::Value(1.0))
        ;

        auto status = options.addSection(section);
        if (!status.isOK()) {
            return status;
        }
    }

    return Status::OK();
}

}  // namespace mongo
